### ISSUE TITLE
net6.0-ios migration

### ISSUE THREAD

**Issue by cosminstirbu** [saturdaymp/XPlugins.iOS.BEMCheckBox#15]
Hello,

The existing version won't work as is with net6.0-ios due to [breaking changes](https://github.com/xamarin/xamarin-macios/issues/13087). These are also documented [here](https://github.com/dotnet/designs/blob/main/accepted/2021/net6.0-tfms/net6.0-tfms.md#why-did-we-not-make-net60-ios-compatible-with-the-existing-xamarin-tfms).

Right now you get the following error - `error NU1202: Package SaturdayMP.XPlugins.iOS.BEMCheckBox 1.4.3 is not compatible with net6.0-ios15.2 (.NETCoreApp,Version=v6.0). Package SaturdayMP.XPlugins.iOS.BEMCheckBox 1.4.3 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)`

Do you have any plans to support net6.0-ios since the GA is scheduled for [Q2 2022](https://github.com/dotnet/maui/wiki/Roadmap)?

The samples from https://github.com/xamarin/xamarin-macios/tree/main/tests/dotnet might be helpful.

Thank you,
Cosmin

**Comment by mrbiggred** [comment]
Hello @cosminstirbu.  Sorry I currently don't have time to to work the XPlugins.iOS.BEMCheckBox but I am happy to work with you, or others, to a PR to make XPlugins.iOS.BEMCheckBox work with .NET 6.  Please feel free to submit a PR and/or ask me any questions about this project.
