### ISSUE TITLE
Incomplete Bitcode error in submission

### ISSUE THREAD

**Issue by jjchoo** [saturdaymp/XPlugins.iOS.BEMCheckBox#2]
Hi,
i have included this nuget package in my project, and i face issue for compiling in bitcode enable. Can i know how can i use this package in bitcode enable project? Thanks.

Below is the error message from submission to iTune Connect.

ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'InstantApp.BoostOrder.Customer.Touch.app/Frameworks/BEMCheckBox.framework/BEMCheckBox' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

**Comment by mrbiggred** [comment]
Hi @jjchoo,

Thank you for bringing this issue to my attention.  Let me check my build process later this week and see if I can fix this issue.

**Comment by mrbiggred** [comment]
The build process when compiling the BEMCheckBox native library is to build it twice.  Once for iphones (ARM) and iphone simulators (i386 and x86/x64).  Both are compiled using the the build command:

```
xcodebuild -project Sample Project/CheckBox.xcodeproj -target BEMCheckBox -configuration Release -sdk iphoneos clean build

xcodebuild -project Sample Project/CheckBox.xcodeproj -target BEMCheckBox -configuration Release -sdk iphonesimulator clean build
```

More details on how I setup the automated build of the BEMCheckBox framework can be found at:

https://nftb.saturdaymp.com/today-i-learned-how-to-automate-objective-c-builds-in-teamcity/

To try and fix the problem I updated the build process to create a archive for the iphoneos build so now that command line looks like:

```
xcodebuild -workspace Sample Project/CheckBox.xcodeproj/project.xcworkspace -scheme BEMCheckBox SYMROOT=/somepath/build OBJROOT=/somepath/build clean archive -sdk iphoneos -configuration Release
```

You can't create a archive for the simulator build.

Hopefully this will fix the bitcode error but I'm not sure yet.  I've just updated the native build and haven't tried to include it in the XPlugins.iOS.BEMCheck project yet.

**Comment by mrbiggred** [comment]
@jjchoo would you mind trying NuGet package 1.4.2-beta0001 on MyGet and see if that fixes the issue?  Thank you.

https://www.myget.org/feed/saturdaymp/package/nuget/SaturdayMP.XPlugins.iOS.BEMCheckBox/1.4.2-beta0001

**Comment by jjchoo** [comment]
Hi Chris,

Thanks for the prompt feedback. I have use
https://github.com/hugoparis19/Xamarin_BemCheckBox temporary for submission
to iOS. When i catch some time, i will try your solution. Thanks for the
help.

Regards,
JJ Choo

**Comment by mrbiggred** [comment]
Assume the issue is fixed and do a release.  Won't be releasing my app to the store anytime soon.  Will create a new issue if this bug crops up again.
