### ISSUE TITLE
Add missing didTapCheckBox event

### ISSUE THREAD

**Issue by PunainenAurinko** [saturdaymp/XPlugins.iOS.BEMCheckBox#4]
Could you please add the missing didTapCheckBox event from BEMCheckBox library. Thanks!

**Comment by mrbiggred** [comment]
@tonk0006 thank you for bringing this issue to my attention.  I'm not sure why I didn't include this event. 
 Let me do some digging and if I don't find a good reason I'll add it.

**Comment by mrbiggred** [comment]
The didTapCheckBox event has been added.  Also updated the example program to use the new event and added some more comments.

**Comment by mrbiggred** [comment]
@tonk0006 you can find a build with the didTapCheckBox event in the MyGet feed at:

https://www.myget.org/feed/saturdaymp/package/nuget/SaturdayMP.XPlugins.iOS.BEMCheckBox/1.4.3-beta0001

PM> Install-Package SaturdayMP.XPlugins.iOS.BEMCheckBox -Version 1.4.3-beta0001 -Source https://www.myget.org/F/saturdaymp/api/v3/index.json

If you have a chance to try the beta release please let me know if it works or not.  I have another issue to fix before I do a proper 1.4.3 release.  Thanks again for notifying me about the missing method.
