### ISSUE TITLE
Selected event for CheckBoxGroup

### ISSUE THREAD

**Issue by Brains** [saturdaymp/XPlugins.iOS.BEMCheckBox#5]
I have set of four `CheckBoxes` inside `CheckBoxGroup` to mimic the behavior of `RadioButtonGroup`.
There are no bindable properties inside `CheckBox` class which I can use with `MvvmCross` (or maybe I just didn't find them?). Thus I wanted to subscribe on `DidTapCheckBox` or `AnimationDidStopForCheckBox` events and `Execute` a command from `ViewModel` on the events.

Events are invoked perfectly without `CheckBoxGroup`. But if I add them to `CheckBoxGroup` then no handlers are called at all, nor `DidTapCheckBox` nor `AnimationDidStopForCheckBox`. It seems like `CheckBoxGroup` consumes a user's tap, changes its own `CheckBoxGroup.SelectedCheckBox` and then suppress the tap propagation, so no `DidTapCheckBox` event is fired on any single `CheckBox`. 

Actually, it's reasonable behavior for a group of controls but the problem is that `CheckBoxGroup` does not expose external event I can subscribe on to know _when_ `CheckBoxGroup.SelectedCheckBox` was changed. Or maybe I should use another mechanism for it? 

```cs
var dev  = new BEMCheckBox();
var test = new BEMCheckBox();
var demo = new BEMCheckBox();
var live = new BEMCheckBox();

dev .DidTapCheckBox += (_,__) => ViewModel.Dev .ExecuteAsync();
test.DidTapCheckBox += (_,__) => ViewModel.Test.ExecuteAsync();
demo.DidTapCheckBox += (_,__) => ViewModel.Demo.ExecuteAsync();
live.DidTapCheckBox += (_,__) => ViewModel.Live.ExecuteAsync();

var boxGroup = new BEMCheckBoxGroup()
{
    //SelectedCheckBox = dev,
    //MustHaveSelection = true
};
boxGroup.AddCheckBoxToGroup(dev);
boxGroup.AddCheckBoxToGroup(test);
boxGroup.AddCheckBoxToGroup(demo);
boxGroup.AddCheckBoxToGroup(live);
```

**Comment by Brains** [comment]
Maybe the problem is in line:
```cs
View.AddSubviews(dev,test,demo,live);
```
However, I can't write:
```cs
View.AddSubview(boxGroup);
```
Because 
```
Error	CS1503	Argument 1: cannot convert from 'SaturdayMP.XPlugins.iOS.BEMCheckBoxGroup' 
to 'UIKit.UIView'
```

**Comment by Brains** [comment]
Sorry, but it's working now. 
Probably the reason of wrong behavior was me.

**Comment by mrbiggred** [comment]
@Brains Thank you for submitting the issue and also solving it.  Do you think you can provide more details on how you solved it in-case someone else has the same problem you did?

Happy holidays and all the best in 2019.

**Comment by Brains** [comment]
I really don't know. 
Today I just checked out the same commit and it worked, no changes were performed with code. 
Maybe restart helped (`Windows, Visual Studio, Mac Virtual Machine`), it's the only thing I can suppose of. 

Happy holidays for you too.

**Comment by Brains** [comment]
Happy holidays for you too.
