### ISSUE TITLE
ExampleClient cannot find namespace SaturdayMP.XPlugins.iOS

### ISSUE THREAD

**Issue by jBijsterboschNL** [saturdaymp/XPlugins.iOS.BEMCheckBox#6]
When compiling the ExampleClient, I'm getting the following build error:

The type or namespace name 'SaturdayMP' could not be found (are you missing a using directive or an assembly reference?)

The SaturdayMP.XPlugins.iOS.BEMCheckBox project has generated the c# classes in the /obj/ios/SaturdayMPXPluginsiOS folder. But the generated public classes are not available in the ExampleClient project.

**Comment by jBijsterboschNL** [comment]
Removing the reference to the iOS Bindings Library and adding a reference to the generated dll (in Release mode!) has fixed the problem.

**Comment by mrbiggred** [comment]
@jBijsterboschNL thank you for bringing up this issue and describing your fix.  If anyone else encounters this issues (i.e. it's not a one off) please let me know so it can be fixed.

**Comment by Lenushta** [comment]
I had same issue and reference to dll worked.
